### ISSUE TITLE
License/Copyright Violation

### ISSUE THREAD

**Issue by zpao** [devmehq/react-qr-code#13]
I don't care that you have forked and are making modifications, that's open source! However I do request that you comply with copyright laws and the license of the original project. You obviously hold your own copyrights to code you write and may license your additions/changes however you choose, but you do need to comply with the license of the original code from which you started. Thanks!

**Comment by meabed** [comment]
Thanks @zpao I will look at the license and do the necessary changes.

**Comment by meabed** [comment]
@zpao I have removed your code from the implementation.

**Comment by zpao** [comment]
You didn't need to remove all code ever written by me in order to do the right thing. I'm thrilled to have my code in use and forked by others to suit their needs. I just want to help ensure the longevity of open source by having myself and others respect copyrights & licenses.
